### ISSUE TITLE
Error message upon installing 7.4.8

### ISSUE THREAD

**Issue by mundmc** [RogueProeliator/indigo-plugins-roku#6]
I love your work- not sure if I should post this here or in the Indigo boards. Upon installing the latest update, I get this message every several seconds:

`
Roku Network Remote Error       Error executing effect for device id 1527675311
Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Roku Network Remote.indigoPlugin/Contents/Server Plugin/RPFramework/RPFrameworkDeviceResponse.py", line 179, in executeEffects
    eval(u'rpDevice.' + effect.updateParam + u'(responseObj, rpCommand)')
  File "<string>", line 1, in <module>
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Roku Network Remote.indigoPlugin/Contents/Server Plugin/rokuNetworkRemoteDevice.py", line 264, in updateDeviceStatusInfo
    channelNumber = deviceInfoDoc.find("channel").find("number").text
AttributeError: 'NoneType' object has no attribute 'text'
`

**Comment by RogueProeliator** [comment]
I answered on the boards, but thanks for reporting here as well -- this is the location I actually track them (even if just me entering them from the boards) to ensure I get everything fixed up.

**Comment by mundmc** [comment]
My pleasure!

Admin @DSM

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
